### ISSUE TITLE
webhook 是否有 message.dropped消息

### ISSUE THREAD

**Issue by zinego** [emqtt/emq-docs-cn#1119]
File: [/zh_CN/advanced/webhook.md](https://www.emqx.io/docs/zh/v4.4/advanced/webhook.html

文档中有message.dropped 的事件, 但是却没有message.dropped的参数.  配置文件中也没有对应的参数. 

![image](https://user-images.githubusercontent.com/36145929/164372685-3b884c16-0a24-4a19-94e5-c565917908fb.png)

**Comment by LenaLenaPan** [comment]
Thanks for raising the issue, this field is removed from the document. @zinego
