### ISSUE TITLE
etc目录是需要自己创建还是相对路径

### ISSUE THREAD

**Issue by lhnanyang** [emqtt/emq-docs-cn#1121]
File: [/zh_CN/advanced/auth-mysql.md](https://www.emqx.io/docs/zh/v4.4/advanced/auth-mysql.html

etc目录是需要自己创建还是相对路径

希望写的清楚一些，谢谢！

**Comment by LenaLenaPan** [comment]
it is the auto-generated directory with the EMQX installation, for more information, you may refer to :https://www.emqx.io/docs/en/v5.0/deploy/install-introduction.html#files-and-directories
