### ISSUE TITLE
"当前客户端总数"的订阅主题不正确

### ISSUE THREAD

**Issue by chenbridge** [emqtt/emq-docs-cn#1137]
File: [/zh_CN/advanced/system-topic.md](https://www.emqx.io/docs/zh/v4.4/advanced/system-topic.html
"当前客户端总数"
文档上的主题是: $SYS/brokers/${node}/stats/connections/count
实际测试主题是: $SYS/brokers/${node}/stats/sessions.count

**Comment by lafirest** [comment]
This has been fixed
