### ISSUE TITLE
添加用户含有空格和删除不了带有空格的用户名

### ISSUE THREAD

**Issue by 1130067815** [emqtt/emq-docs-cn#1142]
File: [/zh_CN/advanced/auth-username.md](https://www.emqx.io/docs/zh/v4.0/advanced/auth-username.html
POST api/v4/auth_username
DELETE api/v4/auth_username/${username}

**Comment by zhongwencool** [comment]
你需要把username给 urlencode一下：
比如：
"xx yy" 经过urlencode后会变成： "xx%20yy"，这样传过来的参数才对。
