### ISSUE TITLE
emq 设备连接后立即断开，采用的是http认证

### ISSUE THREAD

**Issue by chenzhouee** [emqtt/emq-docs-cn#1188]
当换一个clientId之后，能够连上，断开连接后，过一会儿之后，同样的clientId连接后会立刻断开
断开原因：[{"reason":"tcp_closed"}]

**Comment by zhongwencool** [comment]
一般tcp_closed的原因都是客户端主动断开了。
需要提供emqx的具体版本及更详细的日志才能定位。
你可以打开emqx日志调成debug模式。尝试自己定位一下。可以到https://askemq.com/ 上发贴，贴详细的信息，emqx-docs主要是作文档发布用的
