### ISSUE TITLE
Paho Java 已经适配 MQTT 5.0

### ISSUE THREAD

**Issue by faxinter** [emqtt/emq-docs-cn#1316]
File: [/zh_CN/development/java.md](https://www.emqx.io/docs/zh/v5.0/development/java.html)

**Comment by LenaLenaPan** [comment]
Thanks for raising the issue, we have reflected this change in our v5.0 document, https://www.emqx.io/docs/zh/v5.0/gateway/mqttsn.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%BA%93 and here is the link to github page: https://github.com/eclipse/paho.mqtt-sn.embedded-c
