### ISSUE TITLE
exhook client.authorize 一直无法触发

### ISSUE THREAD

**Issue by k8sk-kevin** [emqtt/emq-docs-cn#1344]
File: [/zh_CN/advanced/hooks.md](https://www.emqx.io/docs/zh/v5.0/advanced/hooks.html)

![image](https://user-images.githubusercontent.com/7451606/184932759-0b5cd752-df18-4181-9868-14d3e6287579.png)

**Comment by k8sk-kevin** [comment]
这个是替代旧的 client.check_acl 的功能吧。但现在还不能正常使用。

**Comment by lafirest** [comment]
@HonestarKevin 
Hi, This has been fixed in 5.0.8
https://github.com/emqx/emqx/issues/9022
https://github.com/emqx/emqx/issues/8779

**Comment by k8sk-kevin** [comment]
Thanks
