### ISSUE TITLE
Please provide minimal getting started instructions for using websocket client of dashboard

### ISSUE THREAD

**Issue by spotlesscoder** [emqtt/emq-docs-cn#1345]
I just started EMQX 5.0.4 the first time using docker, configured https, restarted the container, logged in, changed admin password.

Then I went to the integrated websocket client, entered username "admin" and my newly chosen password. Immediately, two messages popped up.
- Connecting to ...
- Disconnected from ...

it seems that the login fails? What needs to be done so that I can start playing with the integrated websocket client?

File: [/en_US/getting-started/dashboard.md](https://www.emqx.io/docs/en/v5.0/getting-started/dashboard.html)

**Comment by zmstone** [comment]
Hi @CodingSpiderFox 
EMQX by default allows anonymous login (or no username/password check at all).
Since you are running EMQX in docker, my guess is maybe the port is not bound to the host ?

```
Listener ssl:default on :8883 started.
Listener tcp:default on :1883 started.
Listener ws:default on :8083 started.
Listener wss:default on :8084 started.
Listener http:dashboard on :18083 started.
```

For websocket client to connect, the listener on port number 8083 should be reachable from the browser.

**Comment by spotlesscoder** [comment]
Thanks for the quick response :)

Tried it again. It works using port 8083, I was using 8084.
I don't know what went wrong but at least 8083 works.

How can I get WSS (8084) to work? I enabled the TLS checkbox, too but still it does not work :/

**Comment by zmstone** [comment]
Hi @CodingSpiderFox 
One can not establish `HTTPS` connection from a browser when the current session in over `HTTP`.
In order to do so, you'll have to enable `https` listener for EMQX dashboard.

We can not provide a minimal `HTTPS` by default because it requires certificates browsers can trust.
If you are to experiment it, here is a minimal example to configure the dashboard:

```
dashboard {
    listeners.https {
        bind = 18083
        enable = true # it's by default false, so true must be set
        keyfile = "etc/certs/key.pem" # private key file
        certfile = "etc/certs/cert.pem" # certificate bundle file
        cacertfile = "etc/certs/cacert.pem" # root CA certs for EMQX to verify clients (browsers), usually not needed.
    }
    default_username = "admin"
    default_password = "secret"
}
```
Would be ideal if you have e.g. let's encrypt certs.
Otherwise you need to make your browser trust the EMQX dashboard endpoint.

**Comment by zmstone** [comment]
@CodingSpiderFox For future questions, you are welcome to ask here: https://github.com/emqx/emqx/discussions
