### ISSUE TITLE
阿里云已经支持tls了建议调整下文档

### ISSUE THREAD

**Issue by 121607691** [emqtt/emq-docs-cn#1418]
File: [/zh_CN/deploy.md](https://www.emqx.io/docs/zh/v3.0/deploy.html)

**Comment by LenaLenaPan** [comment]
This issue is fixed in the v5.0 documentation https://www.emqx.io/docs/zh/v5.0/deploy/cluster/lb.html#%E9%80%89%E6%8B%A9%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%E4%BA%A7%E5%93%81
