### ISSUE TITLE
emqx5.0.4 版本 匿名认证的配置allow_anonymous = false添加后报错，应该添加在哪个位置？

### ISSUE THREAD

**Issue by sea-007** [emqtt/emq-docs-cn#1426]
File: [/zh_CN/advanced/auth.md](https://www.emqx.io/docs/zh/v4.3/advanced/auth.html)

**Comment by sea-007** [comment]
unknown_fields,unknown => <<"alow_anonymous">>,unmatched => <<"acceptors,access_rules...">>}

**Comment by lafirest** [comment]
@sea-007  Hello, the documentation you are watching is for v4.3, for EMQX 5 you should check it [here](https://www.emqx.io/docs/zh/v5.0/security/authn/authn.html#%E8%AE%A4%E8%AF%81%E5%99%A8), the  version 5 has removed anonymous authentication
