### ISSUE TITLE
emqx5.0如何在开启dashboard配置的用户名和密码的认证场景下，对已经使用了SSL认证的客户端连接时取消认证校验？

### ISSUE THREAD

**Issue by sea-007** [emqtt/emq-docs-cn#1437]
File: [/zh_CN/security/authn/authn.md](https://www.emqx.io/docs/zh/v5.0/security/authn/authn.html)

**Comment by lafirest** [comment]
You are talking about three different things:

1. the user && password of the dashboard
2. the user && password of the authn
3. the SSL authentication
There is no relationship between them, please clarify your question first
