### ISSUE TITLE
emqtt_bench文档里的Erlang/OTP版本有问题！

### ISSUE THREAD

**Issue by songzelin-jingran** [emqtt/emq-docs-cn#1461]
File: [/zh_CN/verif/benchmark.md](https://www.emqx.io/docs/zh/v5.0/verif/benchmark.html)
官方的emqtt_bench运行依赖的版本已经至少得22.3了文章里版本有问题，而且我不知道为什么，erlang25版本的去执行make会报下面的错：
/usr/emqtt-bench/rebar3 unlock
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:16: unlock] Error 127
我的erlang25的终端是可以正常使用的，我不知道是erlang版本的问题还是什么问题，本身erlang安装就已经挺费时间的，加上文档写的版本有问题就更让人难受了，请官方尽快核实下最新匹配的erlang版本，注意默认的ubuntu和ali的erlang镜像是22.2.7的，用不了，谢谢！

**Comment by lafirest** [comment]
I'm sorry for this but there is no OTP 25 supports now, I think may you could use the release package directly
