### ISSUE TITLE
找不到 dashboard 的默认登录账号密码

### ISSUE THREAD

**Issue by houkunlin** [emqtt/emq-docs-cn#1546]
File: [/zh_CN/getting-started/dashboard.md](https://www.emqx.io/docs/zh/v5.0/getting-started/dashboard.html)

**Comment by LenaLenaPan** [comment]
Thanks for raising the issue, we just restructured the page, you can find the default user name and password at: https://www.emqx.io/docs/zh/v5.0/getting-started/getting-started.html#%E5%AE%89%E8%A3%85-emqx

**Comment by LenaLenaPan** [comment]
:
