### ISSUE TITLE
Windows installation wrong link, points to MacOS

### ISSUE THREAD

**Issue by vilipetek** [emqtt/emq-docs-cn#1613]
File: [/en_US/deploy/install-windows.md](https://www.emqx.io/docs/en/v5.0/deploy/install-windows.html)
Your windows install link points to MacOS package https://www.emqx.com/downloads/broker/v5.0.14/emqx-5.0.14-macos11-amd64.zip

Please change it to https://www.emqx.com/downloads/broker/v5.0.14/emqx-5.0.14-windows-amd64.tar.gz

Additionally, consider packaging windows version as zip rather than tar.gz

**Comment by LenaLenaPan** [comment]
Hi @vilipetek thanks for raising the issue. The link is just updated, https://www.emqx.io/docs/en/v5.0/deploy/install-windows.html 
For the zip or tar.gz issue, I will talk to the product first and will get back to you if there are any updates. 
I will close this issue for the moment, let me know if you have any further questions.
