### ISSUE TITLE
windows 包下载文件地址挂错了吧

### ISSUE THREAD

**Issue by wxhdavid** [emqtt/emq-docs-cn#1618]
File: [/zh_CN/deploy/install-windows.md](https://www.emqx.io/docs/zh/v5.0/deploy/install-windows.html)

**Comment by LenaLenaPan** [comment]
@wxhdavid 感谢！正确的链接已经上传，稍后会重新构建

**Comment by LenaLenaPan** [comment]
@wxhdavid 相关链接已经更新，感谢反馈 https://www.emqx.io/docs/zh/v5.0/deploy/install-windows.html
