### ISSUE TITLE
咨询一下 java客户端如何实现 $share 消息的订阅

### ISSUE THREAD

**Issue by jone-code** [emqtt/emq-docs-cn#1662]
File: [/zh_CN/development/java.md](https://www.emqx.io/docs/zh/v4.3/development/java.html)

**Comment by JimMoen** [comment]
See also about [Share Subscription](https://www.emqx.io/docs/zh/v4.3/advanced/shared-subscriptions.html#%E5%85%B1%E4%BA%AB%E8%AE%A2%E9%98%85).
For java client, just subscribe the topic as normal.
