### ISSUE TITLE
emqx 产品文档的功能列表问题

### ISSUE THREAD

**Issue by lpe110** [emqtt/emq-docs-cn#1680]
企业版产品文档5.0与开源版文档5.0 的功能列表不一致，以哪个为准啊？
企业版 https://docs.emqx.com/zh/enterprise/v5.0/#功能列表
开源版 https://www.emqx.io/docs/zh/v5.0/#功能列表

**Comment by LenaLenaPan** [comment]
Hi @lpe110 thanks so much for raising the issue, we just fixed the problem, now the feature list on both sites should be consistent now, thanks again!
