### ISSUE TITLE
emqx 保留消息加密方式？

### ISSUE THREAD

**Issue by tingyouwu** [emqtt/emq-docs-cn#1682]
File: [/zh_CN/mqtt/mqtt-retained-messages.md](https://www.emqx.io/docs/zh/v5.0/mqtt/mqtt-retained-messages.html)

获取保留消息发现是加密消息 请问要怎么解析

**Comment by lafirest** [comment]
@tingyouwu, We won't encrypt the `retain message`, I guess they might be encoded by your clients.
