### ISSUE TITLE
emqx.conf配置文件，listeners.tcp.$name.enabled中的$name是什么意思？

### ISSUE THREAD

**Issue by jiangxuhui** [emqtt/emq-docs-cn#1723]
emqx版本：5.0.6
吐槽下：官网写的过于笼统了，实在难以理解，懂得不用看，不懂的还是看不懂
官网解释地址：https://www.emqx.io/docs/zh/v5/admin/cfg.html#authz-http-get
![image](https://user-images.githubusercontent.com/28898668/225232103-2670751c-a361-4320-bab4-226931c3755c.png)

**Comment by jiangxuhui** [comment]
配置文件中大量出现$name,但就是没有解释$name是干嘛的？怎么配置？

**Comment by lafirest** [comment]
@jiangxuhui 
This is just a name placeholder, you can set its value to whatever you like.

**Comment by jiangxuhui** [comment]
> @jiangxuhui This is just a name placeholder, you can set its value to whatever you like.

ok tks~

**Comment by hjianbo** [comment]
@jiangxuhui Thanks for your feedback, we are going to improve our all docs

**Comment by magdsnail** [comment]
> 配置文件中大量出现$name,但就是没有解释$name是干嘛的？怎么配置？

什么意思 ？能否说下
