### ISSUE TITLE
typo error?

### ISSUE THREAD

**Issue by xinyi-xs** [emqtt/emq-docs-cn#1818]
File: [/zh_CN/observability/metrics-and-stats.md](https://www.emqx.io/docs/zh/v5.0/observability/metrics-and-stats.html)
<img width="676" alt="image" src="https://user-images.githubusercontent.com/66231514/232965557-fc97e4be-429b-4754-8c58-06d7d1d1b90d.png">

**Comment by LenaLenaPan** [comment]
@Meggielqk please help to fix this.

**Comment by LenaLenaPan** [comment]
Hi @lee-emqx, thanks for raising the issue, this typo is already fixed, I will close the issue for the moment, do let me know if you have any further issues.
