### ISSUE TITLE
emqx 集群，压测时导致一些集群节点挂掉，没有错误日志

### ISSUE THREAD

**Issue by sz-eason** [emqtt/emq-docs-cn#533]
emqx 某个节点挂掉的问题详情：
    1. client无法连接该节点
    2. dashboard后台管理看到该节点连接无法释放
    3. emqx挂掉后，找不到相关日志
    4. 必须重启 emqx节点才能正常使用
emqx当前开启插件：
    1. emqx_http_auth

**Comment by hjianbo** [comment]
Hi @sz-eason Could you please move this issue to emqx/emqx project, If the problem is not solved.
