### ISSUE TITLE
Suggest splitting the [/en_US/rule/backends.md] 

### ISSUE THREAD

**Issue by Adek06** [emqtt/emq-docs-cn#568]
Can't jump to correct anchor link like this [Save data to TimescaleDB](https://docs.emqx.io/en/enterprise/latest/rule/backends.html#save-data-to-timescaledb)

![error anchor](https://user-images.githubusercontent.com/25602645/101731649-e697b580-3af6-11eb-9b50-09adda913aab.gif)

The possible reason is that the file is too large for the browser to load the anchor.

**Comment by hjianbo** [comment]
According to the grapevine, these pages are already being split.

**Comment by sigming** [comment]
> Can't jump to correct anchor link like this [Save data to TimescaleDB](https://docs.emqx.io/en/enterprise/latest/rule/backends.html#save-data-to-timescaledb)
> 
> ![error anchor](https://user-images.githubusercontent.com/25602645/101731649-e697b580-3af6-11eb-9b50-09adda913aab.gif)
> 
> The possible reason is that the file is too large for the browser to load the anchor.

[https://docs.emqx.io/en/enterprise/latest/rule/backend_timescaledb.html](https://docs.emqx.io/en/enterprise/latest/rule/backend_timescaledb.html)
