### ISSUE TITLE
数据存储配置 404 了

### ISSUE THREAD

**Issue by wivwiv** [emqtt/emq-docs-cn#598]
File: [/zh_CN/README.md](https://docs.emqx.cn/cn/broker/latest/)

![image](https://user-images.githubusercontent.com/25006774/103112638-b244fd00-4691-11eb-8d9b-b5aa4034a36c.png)

在 4.1 版本里面是正确的，指向这个页面

https://docs.emqx.cn/cn/broker/v4.1/backend/backend.html

**Comment by Red-Asuka** [comment]
> File: [/zh_CN/README.md](https://docs.emqx.cn/cn/broker/latest/)
> 
> ![image](https://user-images.githubusercontent.com/25006774/103112638-b244fd00-4691-11eb-8d9b-b5aa4034a36c.png)
> 
> 在 4.1 版本里面是正确的，指向这个页面
> 
> https://docs.emqx.cn/cn/broker/v4.1/backend/backend.html

backend/backend在目录文件中没有，为了搜索结果不会出现目录中不存在的页面，在编译前会根据目录文件，将目录文件中没有的文件删除后编译。

**Comment by wivwiv** [comment]
这一章节应该在目录里面出现的 添加一下即可修复
