### ISSUE TITLE
看不懂https://docs.emqx.cn/broker/latest/advanced/auth-postgresql.html#postgresql-%E8%BF%9E%E6%8E%A5%E4%BF%A1%E6%81%AF

### ISSUE THREAD

**Issue by leqii-com** [emqtt/emq-docs-cn#647]
看到文章写的很长，但是没看懂，因为在控制台根本启动不了emqx_auth_pgsql插件，提示错误如下：
Load plugin emqx_auth_pgsql error: {emqx_auth_pgsql,
                                    {bad_return,
                                     {{emqx_auth_pgsql_app,start,[normal,[]]},
                                      {'EXIT',
                                       {{badmatch,
                                         {error,
                                          {shutdown,
                                           {failed_to_start_child,
                                            emqx_auth_pgsql,
                                            {shutdown,
                                             {failed_to_start_child,
                                              worker_sup,
                                              {shutdown,
                                               {failed_to_start_child,
                                                {worker,1},
                                                invalid_authorization_specification}}}}}}}},
                                        [{emqx_auth_pgsql_app,start,2,
                                          [{file,"emqx_auth_pgsql_app.erl"},
                                           {line,37}]},
                                         {application_master,start_it_old,4,
                                          [{file,"application_master.erl"},
                                           {line,277}]}]}}}}}.

**Comment by zmstone** [comment]
follow up here: https://github.com/emqx/emqx/issues/3789
