### ISSUE TITLE
do acl rules support regex expression?

### ISSUE THREAD

**Issue by baiyuxiong** [emqtt/emq-docs-cn#813]
File: [/zh_CN/advanced/acl.md](https://docs.emqx.cn/broker/v4.3/advanced/acl.html)

**Comment by zmstone** [comment]
converting to discussion.

**Comment by zmstone** [comment]
Hi @baiyuxiong 

regexp based access control is not supported yet in 4.x versions.
in 5.0, we will support regex based filtering before matching/applying rules.
