### ISSUE TITLE
Client拼写错误，该页面中存在5处

### ISSUE THREAD

**Issue by devcheng** [emqtt/emq-docs-cn#864]
File: [/zh_CN/advanced/acl-mnesia.md](https://docs.emqx.cn/broker/v4.3/advanced/acl-mnesia.html)

### Client拼写错误，该页面中存在5处：

1. 添加 ACL 规则
2. 查看已经添加的 ACL 规则
3. 删除 ACL 规则

[http://114.215.109.177/emqx/1.png](http://114.215.109.177/emqx/1.png)
[http://114.215.109.177/emqx/2.png](http://114.215.109.177/emqx/2.png)
[http://114.215.109.177/emqx/3.png](http://114.215.109.177/emqx/3.png)

**Comment by lafirest** [comment]
already fixed
